<style type="text/css">
<!--
.style2 {
	font-size: 12px;
	font-weight: bold;
}
-->
</style>
<table width="559" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><center><img src="images/remagineguy.jpg" width="400" height="95"></center></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><p align="justify"><strong>About Us :: <br>
      <br>
      REMAGINE</strong> (rhymes with "Imagine", formally Neohorizon), is a marketing and software development company. <b>REMAGINE</b> started it's online presence in 2003 and was founded by Ian Ricci and Roger Roberge. <BR><BR>Before <b>REMAGINE</b>, Neohorizon was known for its IRC chat network that was initially formed in 1997. Some members of the Neohorizon team were made up of lead programmers that developed the Unreal IRCD and NeoStats (Now SolarStats). In the second quarter of 2000, Neohorizon broke up, and the IRC Network portion became AxeNet.</p>
      <p align="justify">After the split, Neohorizon focused on designing network infrastructures and network applications along with creating/hosting websites.<br>
        <br>
      After two years of success, Neohorizon branched out into other areas. In 2003, Neohorizon worked along side with Source Marketing, a marketing firm based out of Springfield, Massachusetts, founded by Roger Roberge. Ian Ricci and Roger Roberge decided to combine their efforts as one company and formed <b>REMAGINE</b>.</p>
      <p align="justify"><strong>REMAGINE</strong> is based out of Springfield Massachusetts, the city of homes, Dr. Suess, America's first gasoline powered commercial car, America's first motorcycle (Indian Motorcycle), and let's not forget, the birthplace of Basketball.<br>
      <strong><br>
      REMAGINE</strong> currently offers a wide variety of services such as:</p>
      <p align="justify"><b>Web Design, Marketing, Software Development, On-site Consulting, Network Design, System Analysis and Repair, Graphic creation, Music composition and Site hosting. Whether your business is small or large, REMAGINE can custom tailor to your needs.</b></p>
    <p align="justify"><strong>REMAGINE</strong> doesn&rsquo;t just tailor to clients local within the Massachusetts and Pioneer valley area, we have client&rsquo;s world wide.</p></td>
  </tr>
</table><br>
<hr size="1" color="E4E3DF"><br>
<b>Not-For-Profit Projects ::</b><BR><BR>
During the years, <b>REMAGINE</b> has taken on the task of developing some not-for-profit projects. Some of these projects can be viewed below.<br>
<br>
<table width="559" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="172" valign="top"><a href="http://faculty.stcc.edu/silvestri/rdnslogs/javardnslogs/"><img src="images/rdnslog.gif" width="172" height="54" border="0"></a></td>
    <td width="10">&nbsp;</td>
    <td width="377" valign="top"><div align="justify"><b>RDNSLOGS</b> (originally created <a href="http://faculty.stcc.edu/silvestri/">Antonio Silvestri</a>) is program that reads the log files generated by web servers and produces a cache file of DNS Reverse Lookups that is immediately compatible with the <a href="http://www.analog.cx/"><strong>Analog</strong></a> log file analyzer. The program converts the numeric IP addresses found in log files (or any text file for that matter) to their corresponding host names. <b>REMAGINE</b> ported this program to Java so that it could work on multiple platforms.
<br>
      <br>
      <div align="right"><a href="http://faculty.stcc.edu/silvestri/rdnslogs/javardnslogs/"><strong>RDNSlogs Java</strong></a></div>
    </div></td>
  </tr>
</table>
<br>
<hr size="1" color="E4E3DF">
<br>
<table width="559" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="172" valign="top"><a href="http://www.bookswapper.org"><img src="images/bookswapper.gif" width="204" height="54" border="0"></a></td>
    <td width="10">&nbsp;</td>
    <td width="377" valign="top"><div align="justify">The <b>Book Swapper</b> was developed for Springfield Technical Community College. Its purpose is to make life easier by providing a means of book exchange between students. Although it's still in development, the Book Swapper system plans on being a very useful tool for everyone in the days to come. Stay tuned for updates.<br>
      <br>
      <div align="right"><a href="http://www.bookswapper.org"><strong>Book Swapper</strong></a></div>
    </div></td>
  </tr>
</table>
<br>
<hr size="1" color="E4E3DF">
<p><br>
  <strong>Press Release ::</strong></p>
<p>A collection of <strong>REMAGINE</strong> related news articles.</p>
<table width="550" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="141" valign="top"><CENTER><img src="images/wneclogo.gif" width="140" height="78"></CENTER></td>
    <td width="15">&nbsp;</td>
    <td width="394"><p><strong>04-29-04<br>
        <br>
      Western New England College:<br>
&quot;Grinspoon Foundation honors School of Business entrepreneurs.</strong>&quot;<br>
      <br>
      <a href="http://www.remagine.net/news/wnec/"><strong>Article Page</strong><br>
      <br>
      </a><strong>Western New England College:<br> 
      Communicator:<br>
      A Publication for Alumni and Friends of Western New England College</strong><a href="news/wnec/communicatorfall04.pdf"><br>
        <br>
        <strong>News Letter Page</strong></a> (5.589 MB Download)</p>    </td>
  </tr>
</table><BR><hr size="1" color="E4E3DF"><BR>
<table width="550" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="141" valign="top"><CENTER>
      <a href="http://www.stcc.edu"><img src="images/ministcclogo.gif" width="100" height="102" border="0"></a>
    </CENTER></td>
    <td width="15">&nbsp;</td>
    <td width="394"><strong>01-24-06<br>
      <br>
      </strong>  <strong>Springfield Technical Community College: <br>
      STCC Student Creates Sudoku Puzzle Solution</strong> <br>
      <br>
      <a href="http://remagine.net/news/stcc/articles/sudoku.pdf"><strong>Article Page</strong></a> (57,027 KB Download)<br>    <br>
    <strong>STCC     2006 College Catalog:<br>
    Math, Science and Engineering</strong><br>
    <br>
    <a href="http://www.remagine.net/news/stcc/articles/STCCMSENpp217-233.pdf"><strong>Catalog Page</strong></a> (144,544 KB Download) </td>
  </tr>
</table>
<br>
